---
swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
host: 127.0.0.1:8080
basePath: "/"
tags:
  - name: github-controller
    description: Github Controller
paths:
  "/api/v1/github/{username}":
    get:
      tags:
        - github-controller
      summary: listAccountRepos
      operationId: listAccountReposUsingGET
      produces:
        - "*/*"
      parameters:
        - name: username
          in: path
          description: username
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              "$ref": "#/definitions/RepositoryResponse"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  BranchResponse:
    type: object
    properties:
      commitSha:
        type: string
      name:
        type: string
    title: BranchResponse
  RepositoryResponse:
    type: object
    properties:
      branches:
        type: array
        items:
          "$ref": "#/definitions/BranchResponse"
      ownerLogin:
        type: string
      repositoryName:
        type: string
    title: RepositoryResponse
